services:
  supply-master:
    image: supply-master
    build: .
    container_name: supply-master
    ports:
      - "8080:8080"
    depends_on:
      - supply-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://supply-db:5432/supply-db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  supply-db:
    image: postgres:16.1
    container_name: supply-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: supply-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER" ]
      timeout: 5s
      interval: 5s
      retries: 10
